import shutil
import subprocess
from pathlib import Path
import datetime


__author__ = "Jayaram Kancherla"
__copyright__ = "Jayaram Kancherla"
__license__ = "MIT"

def create_hatchit_repository(project_path: str, description: str, license: str) -> None:
    if description is None:
        description = "Add a short description here!"

    subprocess.run(["uv", "init", "--no-workspace", "--lib", project_path], check=True)
    
    # Clear out the dummy hello function generated by uv init
    init_path = Path(project_path) / "src" / project_path.split("/")[-1].replace("-", "_") / "__init__.py"
    if init_path.exists():
        with open(init_path, "w") as init_f:
            init_f.write("\"\"\"Top-level package initialization.\"\"\"\n")


    modified_files = []
    template_dir = Path(__file__).parent / "templates"

    # Add GitHub Actions
    gh_actions_dir = Path(project_path) / ".github" / "workflows"
    gh_actions_dir.mkdir(parents=True, exist_ok=True)

    for workflow in ["run-tests.yml", "publish-pypi.yml", "pre-commit.yml"]:
        src = template_dir / "uv_github_workflows" / workflow
        dst = gh_actions_dir / workflow
        shutil.copy2(src, dst)
        modified_files.append(dst)

    # Add dependabot.yml
    dependabot_src = template_dir / "github" / "dependabot.yml"
    dependabot_dst = Path(project_path) / ".github" / "dependabot.yml"
    shutil.copy2(dependabot_src, dependabot_dst)
    modified_files.append(dependabot_dst)

    # Add tox.ini
    tox_src = template_dir / "tox" / "uv_tox.ini"
    tox_dst = Path(project_path) / "tox.ini"
    shutil.copy2(tox_src, tox_dst)
    modified_files.append(tox_dst)

    # Add comprehensive .gitignore
    gitignore_src = template_dir / "gitignore" / "gitignore.template"
    gitignore_dst = Path(project_path) / ".gitignore"
    shutil.copy2(gitignore_src, gitignore_dst)
    modified_files.append(gitignore_dst)

    proj_name = Path(project_path).parts[-1]

    try:
        git_name = subprocess.check_output(["git", "config", "user.name"], text=True).strip()
        git_email = subprocess.check_output(["git", "config", "user.email"], text=True).strip()
    except Exception:
        git_name = "First Author"
        git_email = "first.author@example.com"

    # Add top-level root files
    for root_file in ["CHANGELOG.md", "CONTRIBUTING.md", "LICENSE.md", "AUTHORS.md", ".coveragerc", ".readthedocs.yml", "CITATION.cff", ".gitattributes", ".zenodo.json"]:
        src = template_dir / "root" / root_file
        dst = Path(project_path) / root_file
        if src.exists():
            if root_file == "LICENSE.md":
                with open(src, "r") as f:
                    content = f.read()
                with open(dst, "w") as f:
                    f.write(content.replace("REPLACE_PROJECT_NAME", proj_name))
            elif root_file == "AUTHORS.md":
                with open(src, "r") as f:
                    content = f.read()
                with open(dst, "w") as f:
                    f.write(content.replace("First Author <first.author@example.com>", f"{git_name} <{git_email}>"))
            elif root_file == "CITATION.cff":
                name_parts = git_name.split(" ", 1)
                given_names = name_parts[0]
                family_names = name_parts[1] if len(name_parts) > 1 else ""
                today_str = datetime.date.today().strftime("%Y-%m-%d")
                with open(src, "r") as f:
                    content = f.read()
                with open(dst, "w") as f:
                    f.write(content.replace("REPLACE_PROJECT_NAME", proj_name)
                                   .replace("YOUR_FIRST_NAME", given_names)
                                   .replace("YOUR_LAST_NAME", family_names)
                                   .replace("REPLACE_DATE", today_str))
            elif root_file == ".zenodo.json":
                with open(src, "r") as f:
                    content = f.read()
                with open(dst, "w") as f:
                    f.write(content.replace("REPLACE_PROJECT_NAME", proj_name)
                                   .replace("REPLACE_DESCRIPTION", description)
                                   .replace("YOUR_NAME", git_name))
            else:
                shutil.copy2(src, dst)
            modified_files.append(dst)

    # Add pre-commit config
    precommit_src = template_dir / "precommit" / "pre-commit-config.yaml"
    precommit_dst = Path(project_path) / ".pre-commit-config.yaml"
    shutil.copy2(precommit_src, precommit_dst)
    modified_files.append(precommit_dst)

    # Modify README
    readme_path = Path(project_path) / "README.md"

    new_readme = f"""[![PyPI-Server](https://img.shields.io/pypi/v/{proj_name}.svg)](https://pypi.org/project/{proj_name}/)
![Unit tests](https://github.com/YOUR_ORG_OR_USERNAME/{proj_name}/actions/workflows/run-tests.yml/badge.svg)

# {proj_name}

> {description}

A longer description of your project goes here...

## Install

To get started, install the package from [PyPI](https://pypi.org/project/{proj_name}/)

```bash
pip install {proj_name}
```

<!-- biocsetup-notes -->

## Note

This project has been set up using [hatchit](https://github.com/biocpy/biocsetup)
and [uv](https://docs.astral.sh/uv/).
"""

    with open(readme_path, "w") as f:
        f.write(new_readme)
        modified_files.append(readme_path)

    # Add docs
    docs_dir = Path(project_path) / "docs"
    src_docs_dir = template_dir / "docs"
    shutil.copytree(src_docs_dir, docs_dir, dirs_exist_ok=True)
    
    pkg_name = proj_name.replace("-", "_")
    
    conf_py_path = docs_dir / "conf.py"
    if conf_py_path.exists():
        with open(conf_py_path, "r") as f:
            content = f.read()
        with open(conf_py_path, "w") as f:
            f.write(content.replace("REPLACE_PROJECT_NAME", pkg_name).replace("YOUR_NAME", git_name))
        modified_files.append(conf_py_path)
    
    index_md_path = docs_dir / "index.md"
    if index_md_path.exists():
        with open(index_md_path, "r") as f:
            content = f.read()
        with open(index_md_path, "w") as f:
            f.write(content.replace("REPLACE_PROJECT_NAME", proj_name))
        modified_files.append(index_md_path)
        
    for f in docs_dir.glob("**/*"):
        if f.is_file() and f not in modified_files:
            modified_files.append(f)

    # Modify pyproject.toml
    pyprj_path = Path(project_path) / "pyproject.toml"
    with open(pyprj_path, "r") as f:
        pyprj_content = f.read()

    ruff_config = """
[tool.ruff]
line-length = 120
src = ["src"]
exclude = ["tests", "docs"]

[tool.ruff.lint]
extend-ignore = ["F821"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing"
testpaths = ["tests"]
"""

    import re

    # Remove hardcoded version and replace with dynamic versioning
    pyprj_content = re.sub(r'version\s*=\s*"[^"]+"\n', 'dynamic = ["version"]\n', pyprj_content)

    # Replace build-system with hatchling and hatch-vcs
    build_system = """[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.1.0"
"""
    pyprj_content = re.sub(r'\[build-system\].*?build-backend\s*=\s*"[^"]+"\n', build_system, pyprj_content, flags=re.DOTALL)

    pyprj_content = pyprj_content.replace('description = "Add your description here"', f'description = "{description}"')

    with open(pyprj_path, "w") as f:
        f.write(pyprj_content + ruff_config)
        modified_files.append(pyprj_path)

    # tests directory
    tests_dir = Path(project_path) / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    test_file = tests_dir / "test_basic.py"
    
    pkg_name = proj_name.replace("-", "_")
    test_content = f"""import {pkg_name}

def test_import():
    '''Test that the package can be imported.'''
    assert {pkg_name}.__name__ == "{pkg_name}"
"""
    with open(test_file, "w") as f:
        f.write(test_content)
    modified_files.append(test_file)



    # Install dev dependencies
    subprocess.run(["uv", "add", "--dev", "pytest", "pytest-cov", "sphinx", "myst-nb", "furo", "sphinx-autodoc-typehints", "linkify-it-py", "mypy"], cwd=project_path, check=True)

    subprocess.run(["git", "init"], cwd=project_path, check=True)
    subprocess.run(["git", "add", "."], cwd=project_path, check=True)
    subprocess.run(["git", "commit", "-m", "chore: initial setup"], cwd=project_path, check=True)

    print("hatchit complete! 🚀 💥")
